# Project
version=1.1.2
group=dev.xylonity.bonsai.clockwork
java_version=21

# Dependencies
geckolib_version=4.8.1
knightlib_version=1.5.3

# Common
minecraft_version=1.21.1
mod_name=Clockwork
mod_author=Xylonity, Joosh7889
mod_id=clockwork
license=GNU GPLv3
credits=
description=Enhancing mechanics since 1804
minecraft_version_range=[1.21.1, 1.22)

neo_form_version=1.21.1-20240808.144430

parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9

# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.150
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
