# Project
version=1.0.2
group=dev.xylonity.bonsai.clockwork
java_version=17

# Dependencies
geckolib_version=4.7.3
knightlib_version=1.5.0n

# Common
minecraft_version=1.20.1
mod_name=Clockwork
mod_author=Xylonity, Joosh7889
mod_id=clockwork
license=GNU GPLv3
credits=
description=Enhancing mechanics since 1804
minecraft_version_range=[1.20.1, 1.22)

parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.3.0
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
